"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
var express_1 = require("express");
var AnswerController_1 = require("./controllers/AnswerController");
var NpsController_1 = require("./controllers/NpsController");
var People_1 = require("./controllers/People");
var SendMailController_1 = require("./controllers/SendMailController");
var SurveysController_1 = require("./controllers/SurveysController");
var UserController_1 = require("./controllers/UserController");
var router = express_1.Router();
exports.router = router;
var userController = new UserController_1.UserController();
var surveyController = new SurveysController_1.SurveyController();
var sendEmailController = new SendMailController_1.SendMailController();
var answerController = new AnswerController_1.AnswerController();
var npsController = new NpsController_1.NpsController();
var people = new People_1.People("Mary", 24);
router.post("/users", userController.create);
router.get("/users", userController.show);
router.get("/mary", people.walk);
router.post("/surveys", surveyController.create);
router.get("/surveys", surveyController.show);
router.post("/sendMail", sendEmailController.execute);
router.get("/answers/:value", answerController.execute);
router.get("/nps/:survey_id", npsController.execute);
